### ISSUE TITLE
Question about advanced macros

### ISSUE THREAD

**Issue by levkk** [steveklabnik/trpl#2]
Hey there!

Very nice repo!

I have a question about advanced macros: I'm trying to achieve a substitution where both `module::StructName` and `StructName` could be accepted (so I think both a `tt` and a `path`). Is it possible?

Example:

```
macro_rules! my_macro {
    ($this_new_token:tt) => (
        let constant = $this_new_token::from("Hello world!");
    )
}
```

The above example gives me:

```
$this_new_token::from("Hello world!");
               ^^ expected one of `.`, `;`, `?`, or an operator here
```

Thanks!

**Comment by steveklabnik** [comment]
You’d be better served by asking on users.rust-lang.org. Thanks!
